Repository Avaiga/taipy-config, pull requests merged in 2023-01, with the labels that each got.

#34 Refactor/#33 Address mypy issues
  src/taipy/config/_base_serializer.py
  src/taipy/config/checker/_checker.py
  src/taipy/config/config.py
  src/taipy/config/config.pyi
  src/taipy/config/global_app/global_app_config.py
  tests/config/test_section.py
  tests/config/test_section_registration.py
Labels: 📈 Improvement

#32 Fix/ Update _ConfigComparator to check for iterable variable
  src/taipy/config/_config_comparator.py
  tests/config/test_config_comparator.py
Labels: 💥Malfunction

#42 FIx file not found error
  src/taipy/config/version.py
Labels: 🖧 Devops, Core
